steps:
  - id: build image
    name: gcr.io/cloud-builders/docker
    args: [
      'build', 
      '-t', 
      'gcr.io/$PROJECT_ID/myage:$SHORT_SHA', 
      '-f', 
      'Dockerfile', 
      '.'
    ]
  
  - id: push image
    name: gcr.io/cloud-builders/docker
    args: ['push', 'gcr.io/$PROJECT_ID/myage:$SHORT_SHA']