apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: nginx-php
  labels:
    app: nginx-php

spec:
  replicas: 2
  selector:
    matchLabels:
      app: nginx-php
      tier: webserver
  template:
    metadata:
      labels:
        app: nginx-php
        tier: webserver
    spec:
      containers:
      - image: gcr.io/artful-journey-238517/myage@sha256:36bf4ac3520f5bd34ec4d9d3db85ea8295183c4e5e2774aa1e8dfc4252940b3f
        name: nginx-php
        ports:
          - containerPort: 80
