apiVersion: extensions/v1beta1
kind: Deployment

metadata:
  name: nginx-php
  labels:
    app: nginx-php

spec:
  replicas: 3
  selector:
    matchLabels:
      app: nginx-php
      tier: webserver
  template:
    metadata:
      labels:
        app: nginx-php
        tier: webserver
    spec:
      containers:
      - image: gcr.io/artful-journey-238517/myage@sha256:b24bd363bd957b42a708ec93f1ba207db59886b48806d657533f5d353e8056dd
        name: nginx-php
        ports:
          - containerPort: 80
